import type { CandidateProfile, OptimizedResume } from '../types/resume';

export function generateLaTeXCode(profile: CandidateProfile, resume: OptimizedResume): string {
  const p = profile.personalInfo;
  const experiences = profile.experiences || [];
  const projects = profile.projects || [];
  const skills = profile.skills || [];
  const education = profile.education || [];
  const certs = profile.certifications || [];
  const templateId = resume.templateId || 'modern-minimal';

  const esc = (str?: string): string => {
    if (!str) return '';
    return str
      .replace(/&/g, '\\&')
      .replace(/%/g, '\\%')
      .replace(/\$/g, '\\$')
      .replace(/#/g, '\\#')
      .replace(/_/g, '\\_')
      .replace(/~/g, '\\textasciitilde{}');
  };

  return `% =================================================================
% Overleaf LaTeX Resume Template - ${templateId.toUpperCase()}
% Generated by CareerDiscoverAI Platform
% =================================================================
\\documentclass[10pt, letterpaper]{article}

\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\usepackage{xcolor}

\\pagestyle{fancy}
\\fancyhf{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

% Margins & Page Geometry
\\addtolength{\\oddsidemargin}{-0.5in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1in}
\\addtolength{\\topmargin}{-.5in}
\\addtolength{\\textheight}{1.0in}

\\urlstyle{same}
\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

% Section Formatting
\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large\\bfseries
}{}{0em}{}[\\color{blue!80!black}\\vhrulefill{0.4pt}\\vspace{-5pt}]

\\newcommand{\\resumeItem}[1]{
  \\item\\small{
    {#1 \\vspace{-2pt}}
  }
}

\\newcommand{\\resumeSubheading}[4]{
  \\vspace{-2pt}\\item
    \\begin{tabular*}{0.97\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{#1} & #2 \\\\
      \\textit{\\small#3} & \\textit{\\small #4} \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeProjectHeading}[2]{
    \\item
    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\small#1 & #2 \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.15in, label={}]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}

% =================================================================
% DOCUMENT CONTENT
% =================================================================
\\begin{document}

% ---------- HEADING ----------
\\begin{center}
    {\\Huge \\scshape ${esc(p.fullName)}} \\\\ \\vspace{2pt}
    {\\large \\color{blue!80!black} ${esc(p.targetTitle)}} \\\\ \\vspace{4pt}
    \\small 
    ${p.phone ? `${esc(p.phone)} $|$ ` : ''} 
    ${p.email ? `\\href{mailto:${p.email}}{${esc(p.email)}} $|$ ` : ''}
    ${p.linkedin ? `\\href{https://${p.linkedin}}{${esc(p.linkedin)}} $|$ ` : ''}
    ${p.github ? `\\href{https://${p.github}}{${esc(p.github)}}` : ''}
\\end{center}

% ---------- SUMMARY ----------
${p.summary ? `\\section{Professional Summary}
\\small{${esc(p.summary)}}
\\vspace{5pt}` : ''}

% ---------- TECHNICAL SKILLS ----------
\\section{Technical Skills}
\\begin{itemize}[leftmargin=0.15in, label={}]
    \\small{\\item{
     \\textbf{Languages}{: ${skills.filter(s => s.category === 'Languages').map(s => esc(s.name)).join(', ') || 'Java, JavaScript, SQL'}} \\\\
     \\textbf{Frameworks}{: ${skills.filter(s => s.category === 'Frameworks').map(s => esc(s.name)).join(', ') || 'Spring Boot, React, Hibernate'}} \\\\
     \\textbf{Databases \\& Tools}{: ${skills.filter(s => s.category === 'Databases' || s.category === 'Tools').map(s => esc(s.name)).join(', ') || 'PostgreSQL, Redis, Docker, Git'}}
    }}
\\end{itemize}

% ---------- EXPERIENCE ----------
\\section{Work Experience}
\\resumeSubHeadingListStart
${experiences.map(exp => `  \\resumeSubheading
    {${esc(exp.jobTitle)}}{${exp.startDate} -- ${exp.isCurrent ? 'Present' : exp.endDate}}
    {${esc(exp.company)}}{${esc(exp.location)}}
    \\resumeItemListStart
${exp.responsibilities.map(resp => `      \\resumeItem{${esc(resp)}}`).join('\n')}
    \\resumeItemListEnd`).join('\n\n')}
\\resumeSubHeadingListEnd

% ---------- PROJECTS ----------
\\section{Technical Projects}
\\resumeSubHeadingListStart
${projects.map(proj => `  \\resumeProjectHeading
    {\\textbf{${esc(proj.title)}} $|$ \\emph{${esc(proj.techStack?.join(', ') || '')}}}{}
    \\resumeItemListStart
      \\resumeItem{${esc(proj.description)}}
${proj.highlights?.map(h => `      \\resumeItem{${esc(h)}}`).join('\n') || ''}
    \\resumeItemListEnd`).join('\n\n')}
\\resumeSubHeadingListEnd

% ---------- EDUCATION ----------
\\section{Education}
\\resumeSubHeadingListStart
${education.map(edu => `  \\resumeSubheading
    {${esc(edu.institution)}}{${edu.startDate} -- ${edu.endDate}}
    {${esc(edu.degree)} in ${esc(edu.fieldOfStudy)}}{${esc(edu.location)}}`).join('\n')}
\\resumeSubHeadingListEnd

${certs.length ? `% ---------- CERTIFICATIONS ----------
\\section{Certifications}
\\begin{itemize}[leftmargin=0.15in, label={}]
    \\small{\\item{
${certs.map(c => `     \\textbf{${esc(c.title)}} -- ${esc(c.issuer)} (${c.date})`).join(' \\\\\n')}
    }}
\\end{itemize}` : ''}

\\end{document}
`;
}
